### ISSUE TITLE
Set Datapoint timestamp with Strava activity date

### ISSUE THREAD

**Issue by branning** [sethherr/strava-beeminder#1]
Datapoints are being created with the correct distance, and a nicely formatted comment with a link back to the Strava activity, but the timestamp of the datapoint is not set. This means that the datapoints in beeminder will not reflect the correct activity date, unless the strava-beeminder server polls Strava on the same day as the activity.

**Comment by sethherr** [comment]
I assumed I was going to fix this, but it looks like you've forked the repository (and dockerized :smile:). 

So - are you going to submit a pull request, or should I work on this?

**Comment by branning** [comment]
I was running blindly and at full speed at fixing this, but I have zero Rails experience and have no idea what I'm doing. I believe I know what to do as far as adding a line of code, but I would want to test it before submitting a pull request. If you'd rather not wait for me to learn how Rails works, please go ahead and work on it, and I can play along at home.

**Comment by sethherr** [comment]
Fair. This is actually something I'm not going to write tests for, since it's being submitted through the beeminder gem, and writing tests would be a pain. Plus I'm being lazy. 

This isn't what I would recommend taking your first steps with Rails with. If you're looking for resources I could definitely point some out to you though!
